#!/usr/bin/env python3
"""Generates a cursor theme whose pointer is a small ring.

Pen mode wants the pointer to be a small circle rather than an arrow: with a stylus the
pointer *is* a nib, and a ring says where the tip is without an arrowhead covering the
thing you are about to touch.

Drawn rather than borrowed. The first version reused whatever `pencil` the user's theme
happened to ship, which was neither a circle nor guaranteed to exist — a theme without one
got no pen cursor at all. A ring is a few hundred bytes to draw and looks the same in
every theme, which for a *pointer* is exactly what you want.

Written as an Xcursor file directly because `xcursorgen` is not installed here and the
format is a header, a table of contents, and one premultiplied ARGB blob per size.

Usage:  pen-cursor.py <theme-name> [parent-theme]
Prints the generated theme's name on success.
"""

import os
import struct
import sys

# One entry per nominal size a theme is expected to answer for. The compositor asks for
# the size the user configured and falls back to the nearest.
NOMINAL_SIZES = (16, 20, 24, 32, 48, 64)

IMAGE_TYPE = 0xFFFD0002
XCURSOR_MAGIC = 0x72756358


def coverage(distance, edge, thickness):
    """Antialiased coverage of a ring of `thickness` whose outer edge is at `edge`."""
    if thickness <= 0:
        return 0.0
    outside = min(1.0, max(0.0, (edge + 0.5) - distance))
    inside = min(1.0, max(0.0, distance - (edge - thickness - 0.5)))
    return min(outside, inside)


def ring_pixels(size):
    """A small ring, centred, as premultiplied ARGB.

    Two strokes rather than one: a white ring inside a dark one, so the cursor is legible
    on a dark wallpaper and on a white page without knowing which it is over. The same
    trick every drawing application uses for its brush cursor.
    """
    # Well inside the box, so it reads as a small dot rather than as something the size of
    # an arrow — a big ring would hide what it is pointing at.
    outer = size * 0.28
    dark_thickness = max(1.0, size / 16.0)
    inner = outer - dark_thickness
    light_thickness = max(1.0, size / 20.0)
    centre = (size - 1) / 2.0

    pixels = []
    for y in range(size):
        for x in range(size):
            dx = x - centre
            dy = y - centre
            distance = (dx * dx + dy * dy) ** 0.5

            light = coverage(distance, inner, light_thickness)
            dark = coverage(distance, outer, dark_thickness)

            if light > 0:
                red = green = blue = 255
                alpha = light
            elif dark > 0:
                red = green = blue = 0
                alpha = dark * 0.85
            else:
                pixels.append(0)
                continue

            a8 = int(round(alpha * 255))
            pixels.append((a8 << 24)
                          | ((red * a8 // 255) << 16)
                          | ((green * a8 // 255) << 8)
                          | (blue * a8 // 255))
    return pixels


def write_xcursor(path, sizes):
    images = []
    for size in sizes:
        pixels = ring_pixels(size)
        hot = size // 2
        # chunk header: size, type, subtype, version, then the image fields
        body = struct.pack("<IIIIIIIII", 36, IMAGE_TYPE, size, 1,
                           size, size, hot, hot, 0)
        body += struct.pack("<%dI" % len(pixels), *pixels)
        images.append((size, body))

    header = struct.pack("<IIII", XCURSOR_MAGIC, 16, 0x00010000, len(images))
    offset = len(header) + 12 * len(images)

    toc = b""
    for size, body in images:
        toc += struct.pack("<III", IMAGE_TYPE, size, offset)
        offset += len(body)

    with open(path, "wb") as handle:
        handle.write(header)
        handle.write(toc)
        for _, body in images:
            handle.write(body)


def main():
    if len(sys.argv) < 2:
        print("usage: pen-cursor.py <theme-name> [parent-theme]", file=sys.stderr)
        return 2

    name = sys.argv[1]
    parent = sys.argv[2] if len(sys.argv) > 2 else ""

    base = os.environ.get("XDG_DATA_HOME") or os.path.expanduser("~/.local/share")
    out = os.path.join(base, "icons", name)
    cursors = os.path.join(out, "cursors")
    os.makedirs(cursors, exist_ok=True)

    with open(os.path.join(out, "index.theme"), "w") as handle:
        handle.write("[Icon Theme]\n")
        handle.write("Name=%s\n" % name)
        handle.write("Comment=A small ring for a pointer, generated by illogical-impulse\n")
        # Everything that is not the plain pointer — the I-beam over text, the resize
        # arrows on a window edge — still means what it always meant with a pen in your
        # hand, so it is inherited rather than redrawn.
        if parent:
            handle.write("Inherits=%s\n" % parent)

    write_xcursor(os.path.join(cursors, "default"), NOMINAL_SIZES)
    for alias in ("left_ptr", "arrow", "top_left_arrow"):
        target = os.path.join(cursors, alias)
        if os.path.lexists(target):
            os.remove(target)
        os.symlink("default", target)

    print(name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
