pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Layouts
import qs.services
import qs.modules.common
import qs.modules.common.functions
import qs.modules.common.widgets

/**
 * The footer row of a Hyprland section: the only place anything set elsewhere gets undone.
 *
 * Every row already wears its own pill - Overridden, Set here, Set by hand - the moment
 * something about it is worth saying, so this footer used to repeat the same fact as a full
 * sentence per key underneath. That second telling is what actually cluttered the page; the
 * pill already answered "what", so what is left for the footer to earn its place is "what can
 * be done about it" - the reset and cleanup actions - said once, briefly, for the section.
 *
 * One per ContentSection rather than one per control - a chip under every row would be noise,
 * and most rows have nothing to report. Declared as the section's last child so it joins the
 * same rounded group, and it hides itself when there is nothing to say (an invisible sibling
 * does not break the grouping, so an untouched section looks exactly as it did before).
 */
Rectangle {
    id: root

    /// Every key the section owns. The note reports on whichever of them has something to say.
    property var keys: []
    /// Extra lines the section wants in the same footer, as `{ icon, text }`. For the things a
    /// key's own state cannot say - an option that moved to another syntax, a setting that only
    /// applies on some hardware - so a section still has one place where the caveats live.
    property var notes: []

    /// Everything below that feeds a Repeater goes through ObjectUtils.keep: the states are
    /// rebuilt whenever any layer moves, and a model that kept its identity keeps its rows.
    property var _memo: ({})

    // Defensive: a caller whose own `keys` binding throws hands this undefined, and one bad
    // reference there would otherwise take out all six properties below it as well.
    readonly property var optionStates: Array.from(root.keys ?? [])
        .filter(key => String(key ?? "") !== "").map(key => HyprlandGui.resolve(key))
    readonly property var managed: ObjectUtils.keep(root._memo, "managed",
        root.optionStates.filter(state => state.isManaged).map(state => ({ "key": state.key })))
    readonly property var inherited: root.optionStates.filter(state => state.inherited !== null)
    readonly property var shadowed: root.optionStates.filter(state => state.shadowedBy !== null)
    readonly property var shellOwned: root.optionStates.filter(state => state.shellOwnedBy !== "")

    function shortName(key: string): string {
        return String(key).split(":").slice(1).join(":") || key;
    }

    /**
     * One line, not one per key - for the two cases that can't name a culprit.
     *
     * The row that owns each key already says what happened to it - that is what the pill next
     * to the control is for - so repeating "Overridden" as a full sentence per key was the actual
     * clutter. It also used to go further than the page can back up: everything landing in
     * `shadowed` is whatever `shellOverrides/main.lua` holds at reload, and that file is
     * regenerated by several unrelated things - the theme's own repo defaults, the Welcome tour's
     * keyboard-layout step, an actual Mode - with no record here of which one wrote which line.
     * Naming "Modes, Game Mode or the screen shader" was a guess that was usually wrong, so this
     * says only what is true for every case: something outside this page has the last word.
     *
     * A hand-written line is different - real, visible, actionable - and keeps its own row below
     * instead of folding in here, because saying exactly where it lives is something this page
     * can back up.
     */
    readonly property string summary: {
        const total = root.shellOwned.length + root.shadowed.length;
        if (total === 0) return "";
        if (root.shellOwned.length > 0 && total === root.shellOwned.length)
            return Translation.tr("%1 setting(s) here belong to the shell and can't be set from this page.").arg(total);
        return Translation.tr("%1 setting(s) here are set outside this page, and win over it.").arg(total);
    }

    /// Removing a hand-written line is only offered once this page sets the key too, because
    /// then taking it out changes nothing. Otherwise it would silently reset the setting.
    readonly property var removable: ObjectUtils.keep(root._memo, "removable",
        root.inherited.filter(state => state.isManaged && state.inherited.removable)
            .map(state => ({ "key": state.key })))

    /**
     * Shadowed keys this page can actually do something about.
     *
     * `shellOverrides/main.lua` loads after every custom file, so a line sitting in it always
     * wins - setting the key here saves the change, but nothing about it ever takes effect,
     * which is what made the page look like it silently refused the edit. The keys the shell
     * itself owns (gaps, border, rounding, the accent colours) are meant to be re-asserted like
     * that on every reload, so clearing their line would just have it rewritten back; every other
     * key sitting in that file usually got there once - a Welcome-tour step, an old default - and
     * nothing has touched it since, so clearing it is what actually lets a change here stick.
     */
    readonly property var clearable: ObjectUtils.keep(root._memo, "clearable",
        root.shadowed.filter(state => state.shellOwnedBy === "").map(state => ({ "key": state.key })))

    /// `{ icon, text, always }`. A note marked `always` is a warning about what is about to
    /// happen - a key that is already taken, a session with no way left to open a terminal - so
    /// it is shown whether or not advanced mode is on. Everything else is background.
    readonly property var extraNotes: ObjectUtils.keep(root._memo, "extraNotes",
        Array.from(root.notes ?? []).filter(note => root.advanced || note.always === true))

    /**
     * Advanced mode is the difference between a footer that explains and one that acts.
     *
     * The prose here is true and occasionally useful, and it was on screen under every section
     * of every tab whether or not it had anything to do with what was being changed. Reading a
     * settings page should not be reading. So without advanced mode this footer is only the
     * buttons - reset, clean up, let this page win - and the reset is one button for the whole
     * section rather than one per key, because "which of these four keys do I want back" is a
     * question only somebody in advanced mode is asking.
     */
    readonly property bool advanced: Config.options.hyprland.advancedSettings

    readonly property bool hasActions: root.managed.length > 0 || root.removable.length > 0
        || root.clearable.length > 0
    readonly property bool hasProse: root.extraNotes.length > 0
        || (root.advanced && (root.summary !== "" || root.inherited.length > 0))

    visible: root.hasActions || root.hasProse
    Layout.fillWidth: true
    implicitHeight: visible ? layout.implicitHeight + 20 : 0
    color: root.shellOwned.length > 0 || root.shadowed.length > 0
        ? Appearance.colors.colSurfaceContainerHigh : Appearance.colors.colLayer2

    // Only the bottom corners need thinking about: the note is the last row of its group, and
    // never the first, because a section always has controls above it.
    readonly property bool isLast: {
        const owner = root.parent;
        if (!owner) return true;
        const siblings = owner.children;
        let seen = false;
        for (let i = 0; i < siblings.length; i++) {
            if (siblings[i] === root) {
                seen = true;
                continue;
            }
            if (!seen || !siblings[i].visible) continue;
            return typeof siblings[i].topLeftRadius === "undefined";
        }
        return true;
    }

    topLeftRadius: Appearance.rounding.verysmall
    topRightRadius: Appearance.rounding.verysmall
    bottomLeftRadius: root.isLast ? Appearance.rounding.large : Appearance.rounding.verysmall
    bottomRightRadius: root.isLast ? Appearance.rounding.large : Appearance.rounding.verysmall

    /// The confirmation lives on the hub, which is the only thing here that can host a dialog.
    function askToRemove(key: string) {
        let node = root.parent;
        while (node) {
            if (node.requestDropInherited !== undefined) {
                node.requestDropInherited(key);
                return;
            }
            node = node.parent;
        }
    }

    ColumnLayout {
        id: layout
        anchors {
            left: parent.left
            right: parent.right
            top: parent.top
            leftMargin: 16
            rightMargin: 16
            topMargin: 10
        }
        spacing: 6

        RowLayout {
            Layout.fillWidth: true
            spacing: 8
            visible: root.advanced && root.summary !== ""

            MaterialSymbol {
                Layout.alignment: Qt.AlignTop
                text: "layers"
                iconSize: Appearance.font.pixelSize.normal
                color: Appearance.colors.colSubtext
            }

            StyledText {
                Layout.fillWidth: true
                text: root.summary
                font.pixelSize: Appearance.font.pixelSize.smaller
                color: Appearance.colors.colSubtext
                wrapMode: Text.WordWrap
            }
        }

        // A hand-written line names a real file and line number, so - unlike the shadowed/shell
        // cases folded into the summary above - it keeps its own row instead of a vague count.
        Repeater {
            model: root.advanced ? root.inherited : []

            delegate: RowLayout {
                id: inheritedRow
                required property var modelData

                readonly property string where: Translation.tr("%1 line %2")
                    .arg(modelData.inherited.file).arg(modelData.inherited.line)

                Layout.fillWidth: true
                spacing: 8

                MaterialSymbol {
                    Layout.alignment: Qt.AlignTop
                    text: "edit_note"
                    iconSize: Appearance.font.pixelSize.normal
                    color: Appearance.colors.colSubtext
                }

                StyledText {
                    Layout.fillWidth: true
                    text: inheritedRow.modelData.isManaged
                        ? Translation.tr("%1 is also set by hand at %2. The value above wins.")
                            .arg(root.shortName(inheritedRow.modelData.key)).arg(inheritedRow.where)
                        : Translation.tr("%1 is set by hand at %2.")
                            .arg(root.shortName(inheritedRow.modelData.key)).arg(inheritedRow.where)
                    font.pixelSize: Appearance.font.pixelSize.smaller
                    color: Appearance.colors.colSubtext
                    wrapMode: Text.WordWrap
                }
            }
        }

        // Call-site notes are specific facts a key's own state can't say by itself - an option
        // that moved to another syntax, one that only applies on some hardware - so unlike the
        // summary above, each of these still earns its own line.
        Repeater {
            model: root.extraNotes

            delegate: RowLayout {
                required property var modelData

                Layout.fillWidth: true
                spacing: 8

                MaterialSymbol {
                    Layout.alignment: Qt.AlignTop
                    text: modelData.icon
                    iconSize: Appearance.font.pixelSize.normal
                    color: Appearance.colors.colSubtext
                }

                StyledText {
                    Layout.fillWidth: true
                    text: modelData.text
                    font.pixelSize: Appearance.font.pixelSize.smaller
                    color: Appearance.colors.colSubtext
                    wrapMode: Text.WordWrap
                }
            }
        }

        Flow {
            Layout.fillWidth: true
            spacing: 6
            visible: root.managed.length > 0 || root.removable.length > 0 || root.clearable.length > 0

            NoteButton {
                visible: !root.advanced && root.managed.length > 0
                label: Translation.tr("Reset")
                buttonIcon: "undo"
                onClicked: {
                    HyprlandGui.batch(() => {
                        for (const entry of root.managed) HyprlandGui.resetKey(entry.key);
                    });
                }
            }

            Repeater {
                model: root.advanced ? root.managed : []

                delegate: NoteButton {
                    required property var modelData

                    label: Translation.tr("Reset %1").arg(root.shortName(modelData.key))
                    buttonIcon: "undo"
                    onClicked: HyprlandGui.resetKey(modelData.key)
                }
            }

            Repeater {
                model: root.removable

                delegate: NoteButton {
                    required property var modelData

                    label: Translation.tr("Remove the old %1 line").arg(root.shortName(modelData.key))
                    buttonIcon: "delete_sweep"
                    onClicked: root.askToRemove(modelData.key)
                }
            }

            Repeater {
                model: root.clearable

                delegate: NoteButton {
                    required property var modelData

                    label: Translation.tr("Let %1 win here").arg(root.shortName(modelData.key))
                    buttonIcon: "layers_clear"
                    onClicked: HyprlandGui.clearShadowing([modelData.key])
                }
            }
        }
    }

    component NoteButton: RippleButton {
        id: noteButton

        property string label: ""
        property string buttonIcon: ""

        implicitHeight: 28
        implicitWidth: noteButtonRow.implicitWidth + 20
        buttonRadius: Appearance.rounding.full
        colBackground: Appearance.colors.colSecondaryContainer
        colBackgroundHover: Appearance.colors.colSecondaryContainerHover
        colRipple: Appearance.colors.colSecondaryContainerActive

        contentItem: RowLayout {
            id: noteButtonRow
            spacing: 4

            MaterialSymbol {
                Layout.leftMargin: 10
                text: noteButton.buttonIcon
                iconSize: 14
                color: Appearance.colors.colOnSecondaryContainer
            }

            StyledText {
                Layout.rightMargin: 10
                text: noteButton.label
                font.pixelSize: Appearance.font.pixelSize.smaller
                color: Appearance.colors.colOnSecondaryContainer
            }
        }
    }
}
